title: Introduction_for_all_uestcers
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

# 仓库信息
baseurl: "/Introduction_for_all_uestcers"  # 仓库名，斜杠开头
url: "https://teddyfight0.github.io"  # 你的 GitHub Pages 域名

plugins:
  - jekyll-seo-tag

# 左侧导航栏配置
# 你需要把每一章内容拆分成单独的 md 文件
# 例如 preface.md, school.md, economy.md, major.md, study.md, ai.md, growth.md, reference.md
# 每个 md 文件的顶部加上 front matter，例如
# ---
# title: 前言
# nav_order: 1
# ---

# Just the Docs sidebar 配置
nav:
  - title: 前言
    url: /preface
  - title: 学校概况
    url: /school
    children:
      - title: 衣食住行
        url: /school#衣食住行
      - title: 组织结构
        url: /school#学校的组织结构和对学生直接相关的机构
  - title: 学会生存
    url: /survive
    children:
      - title: 社会主义市场经济
        url: /economy#社会主义市场经济
      - title: 商品经济与资本主义
        url: /economy#商品经济的本质是什么
      - title: 培养方案
        url: /major#培养方案到底为谁服务
      - title: 转专业
        url: /major#转专业吗
      - title: 选课
        url: /major#选课
      - title: 升学
        url: /study#升学
      - title: 勤工助学
        url: /money#勤工助学
  - title: 实用技能
    url: /skills
    children:
      - title: 英语及其他外语
        url: /language#谈外语
      - title: 科学上网
        url: /ai#科学上网
      - title: 用ai工作
        url: /ai#用ai工作
      - title: 资料收集
        url: /growth#站在前人的肩膀上
      - title: 上课
        url: /growth#上课
      - title: 速成的魅力
        url: /growth#速成的魅力
      - title: 选合适的组员
        url: /growth#选合适的组员
      - title: 报告的魅力
        url: /growth#报告（PPT）的魅力
      - title: 打卡
        url: /growth#打卡
      - title: 网页插件与脚本
        url: /growth#网页插件与脚本
      - title: 实验报告
        url: /growth#实验报告
  - title: 实用技能
    url: /personaltalk
    children:
      - title: 学习没有捷径
        url: /personaltalk#学习没有捷径
      - title: 认清竞赛的真面目
        url: /personaltalk#认清竞赛的真面目
      - title: 前景与规划
        url: /personaltalk#前景与规划
      - title: 简历
        url: /personaltalk#简历
      - title: 危险的改革者
        url: /personaltalk#危险的改革者（xsz，djs）
      - title: 勇气
        url: /personaltalk#勇气
      - title: 失败
        url: /personaltalk#失败
      - title: 认清自己的能力
        url: /personaltalk#认清自己的能力
  - title: 参考文献
    url: /reference


